### ISSUE TITLE
Feature request: overload parameters from command line

### ISSUE THREAD

**Issue by yartem** [neuro-inc/neuro-flow#11]
```
$ neuro-flow run jupyter --preset=cpu-small
```

**Comment by yartem** [comment]
To ease development. When working with makefile, I used to specify parameters via env vars very often. Example: you need to find appropriate batch-size that fits your job (so that it does not fail with GPU out-of-memory). Thus, you want to run multiple experiments to adjust this, better when without need to edit yaml.

**Comment by asvetlov** [comment]
Nope. The editing is fine in your context.

**Comment by asvetlov** [comment]
You can override names from  `params` config section
