### ISSUE TITLE
Bake name is confusing

### ISSUE THREAD

**Issue by mariyadavydova** [neuro-inc/neuro-flow#135]
When I bake a batch, I see 
`Bake demo_jobs/matrix_2020-10-16T12:23:55+00:00_dab655 is created`
However, when I run 
`neuro-flow inspect demo_jobs/matrix_2020-10-16T12:23:55+00:00_dab655`
I get an error because, in fact, the name of the back doesn't contain the project name:
`neuro-flow inspect matrix_2020-10-16T12:23:55+00:00_dab655`
works as expected.

**Comment by asvetlov** [comment]
I suggest a new message template, e.g. `Bake matrix_2020-10-16T12:23:55+00:00_dab655 for project demo_jobs is created`
I believe the project name is important and should be printed.
Bake ID should go first, sure.

**Comment by mariyadavydova** [comment]
Totally agree!
