### ISSUE TITLE
Cache attribute of stateful action is ignored

### ISSUE THREAD

**Issue by romasku** [neuro-inc/neuro-flow#219]
Stateful actions allow to define cache strategy:
```
kind: stateful
cache:
  strategy: none
```
But current implementation ignores this setting.

**Comment by asvetlov** [comment]
Interesting.
Do we really want to cache them?
What is the use case?

**Comment by romasku** [comment]
If you suggest to disable caching for stateful tasks, I +1 for that. Stateful tasks will often deinitialize their outputs, so using cached values can cause errors.
