### ISSUE TITLE
Incorrect brake record breaks `neuro-flow bakes`

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/neuro-flow#346]
In this setup, IDK what went wrong (maybe the `ERROR: Bad Gateway` or whatever what is not debuggable ATM), but it turned out that one of my bake records became broken (the last one):
![image](https://user-images.githubusercontent.com/32543098/113434761-383bb700-93ea-11eb-871e-99c42e330bda.png)
Why it is broken from my point of view? Since it doesn't have the `*.attempt` file.
Does my assumption correct?

As a result, I cannot list my bakes anymore without an intrusion to NF internals and deleting bake by hands:
![image](https://user-images.githubusercontent.com/32543098/113434733-2d812200-93ea-11eb-8bf8-cabde65fbaee.png)

Probably, our generic approach to handle such situations as` Bake <id> is malformed, skipping` should cover this case too.
Also, let's add more info to the error message ("ERROR: unreachable" has no sense)

**Comment by romasku** [comment]
This issue should not be reproducible with new API based storage. I think we close this.
