### ISSUE TITLE
Allow expressions in params

### ISSUE THREAD

**Issue by romasku** [neuro-inc/neuro-flow#434]
Currently, params do not support expressions, but sometimes it can be useful:

For example (real use case), if one job takes HTTP URL as an input, and by default, it should be HTTP URL to another job:
```
param:
   inference_url: ${{ inspect_job('deploy_inference_platform').http_url }}
```
I think there other use-cases also exist.

**Comment by YevheniiSemendiak** [comment]
Brilliant feature 👍
