### ISSUE TITLE
Validator does not pass if action contained the image definition was used several times 

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/neuro-flow#439]
Imagine having batch A, which uses a different batch B several times as an action.

If batch B contains image definition, the validator will assume, that the same image was defined several times and therefore will throw an error `image ref is duplicated`, which is actually wrong.

**Comment by romasku** [comment]
Hmm, this is an interesting issue. Technically, image build can depend on action `inputs` and produce different images for different invocations of the same action. I assume this will not be the case for almost all real-world batches, but please correct me if I wrong.

I think for now we can just allow the same ref from different invocations of the same action and ignore possible consequences. When we will have time we can add an additional check during bake execution - if we are trying to build an image with the same ref with different params then throw an error.

**Comment by romasku** [comment]
Currently, image refs are evaluated early, so they cannot be based on values from the `inputs` context. This allows checking that refs are unique early and then use refs as unique identifiers of images through all DAG.

**Comment by YevheniiSemendiak** [comment]
Sounds reasonable. Let's just follow your earlier suggestion.
