### ISSUE TITLE
Bake inspect reports that image build is "pending" instead of "built" if the image was previously built

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/neuro-flow#490]
Example.
All images for the batch were build in this batch:
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/32543098/122926390-79e85800-d370-11eb-99c0-61066a3d6cc1.png">

By design, we do not rebuild images in subsequent bakes (if not configured otherwise).
However, in the `neuro-flow inspect <bake>` report, those images hang in the state `pending`, instead of `cached` (with Builder ID, if it's retrievable). 
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/32543098/122926807-e8c5b100-d370-11eb-94aa-14f7eed225dc.png">

**Comment by romasku** [comment]
Unfortunately, we cannot deduce `builder id` for cached images - as the image itself has no info about the builder, it can always be the case that the user manually rebuilds the image (for example, using `neuro-flow build <image>`), so I think it better to give no information than to give "not always correct" one.

**Comment by YevheniiSemendiak** [comment]
Got it, you are right. Good idea for adding `cached` 👍 
Thank you!
