### ISSUE TITLE
Unclear how to set `flow.project_id`

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/neuro-flow#510]
AFAIK, there are several methods to set the `flow.project_id` parameter in live mode.
1. Auto-generated based on the folder name
2. within the live.yaml file, set `id` (or `flow_id`?) field
3. within the project.yaml set `id` value

In which order this info will be applied, if the 2nd and 3rd options are set?
Let's enhance the docs.

**Comment by romasku** [comment]
Hello,

2 and 3 are different:
- top level `id` in flow config files (both live and batch) sets value for `${{ flow.flow_id }}`.
- top level `id` in project config file sets value for `${{ flow.project_id }}` and `${{ project.id }}.

I'll update the docs.

**Comment by romasku** [comment]
Sure, I've [updated the docs](https://github.com/neuro-inc/neuro-flow/commit/3c2475391f1ec131256378d5c3de2b43a0723319).

**Comment by YevheniiSemendiak** [comment]
Awesome! Thank you a lot! 💪
