### ISSUE TITLE
Need more details in bake logs

### ISSUE THREAD

**Issue by mariyadavydova** [neuro-inc/neuro-flow#61]
The bake logs need details, at least statuses of tasks, and their outputs.
Without this information to get the job output I have to check the logs manually by copying the job ID.

**Comment by asvetlov** [comment]
Statuses are added by #76

Do you mean values of `::set-output ...::` commands by job outputs?
Or you are talking about job logs? (which can be pretty long, interleaved logs from concurrent jobs are not very readable).

**Comment by mariyadavydova** [comment]
I mean values of `::set-output`.
