### ISSUE TITLE
'project.yml' seems to be ignored in our example

### ISSUE THREAD

**Issue by mariyadavydova** [neuro-inc/neuro-flow#64]
As 'flow.project_id' is resolved to 'demo_jobs' instead of 'neuro_flow_demo' both in live and batch modes.

**Comment by romasku** [comment]
Seems like `neuro-flow` currently expected it to be placed under workspace folder (`examples/neuro-jobs` directory), not under config folder (`examples/neuro-jobs/.neuro`).

**Comment by asvetlov** [comment]
I believe, now everything is good
