### ISSUE TITLE
Allow project sharing configuration

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/neuro-flow#659]
Our NF projects might have a [role](https://neu-ro.gitbook.io/neuro-flow/reference/project-configuration-syntax#role) associated with the project.
We state this role might be shared with other users via `neuro acl grant ...` in the same doc.
However, this does not work, since it is unclear what's the role:
![image](https://user-images.githubusercontent.com/32543098/141300387-b38837a7-53ab-4e03-9d05-ee74e8eec597.png)

This especially becomes hard since we are [not able](https://github.com/neuro-inc/platform-client-python/issues/2395) to list the roles.

What if we add some commands to the CLI, which will:
1. Share the project with other users `neuro-flow project share <user> read|write|manage`
2. Share the defined resources in the project description with the associated project role `neuro-flow project grant-resources-access` (or something like this).

**Comment by mariyadavydova** [comment]
NTBF, as we reconsider the project sharing
