### ISSUE TITLE
Make jobs dependent on volumes sync

### ISSUE THREAD

**Issue by mariyadavydova** [neuro-inc/neuro-flow#74]
The use-case is the following: we keep the code in a volume and mount this volume in the training job; it is very easy to forget to upload the volume before running a job.
We need some way to tell in YAML, that before running a given job we always need to upload the given volume(s).

**Comment by asvetlov** [comment]
How to figure out if the volume was uploaded or not?
How to figure out if the volume is out of sync with local files?

**Comment by mariyadavydova** [comment]
I don't expect a really intelligent solution here. Simply, always upload a volume before running a job. Otherwise, a user has always to run `neuro-flow upload code` before running `neuro-flow run train`, which is a reasonable source for the human error (too easy to forget, if you run a lot of experiments).

**Comment by asvetlov** [comment]
got you

**Comment by asvetlov** [comment]
`upload()` function solves the issue
