### ISSUE TITLE
`neuro-flow project init`

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/neuro-flow#850]
The behavior of implemented feature might look as follows:
- check whether cookiecutter CLI presents
  - if not: install it via pip/pipx
- perform cookiecutter CLI call with the corresponding template address
- [create](https://github.com/neuro-inc/neuro-flow/blob/9d290fda4fba3c105b7f2d21b7120037cc280c7b/neuro_flow/storage/api.py#L376-L390) a project

Caveats needed discussion:
- We use the latest `cookiecutter` package while installing it, or hardcoding the version? Both look ugly. Yet another alternative: we could add `[options.extras_require]` to `setup.cfg` with `cookiecutter` in it, wdyt @asvetlov?

- What happens if the user creates the project with an already existing ID, i.e. a duplicate? Ideally, we should ban it, or ask to remove the previous one (or use `--recreate`). This will not harm us now, but in the future - might. wdyt, @asvetlov, @romasku?

**Comment by andriihomiak** [comment]
Currently, creation of project with existing name raises an error. It is possible to reuse the project, but it might be not intuitive. 

To support something like `--recreate` we need to be able to remove the project, but there is no such functionality yet.

**Comment by YevheniiSemendiak** [comment]
>  creation of project with existing name raises an error
Meaning, within the neuro-flow API?
